### ISSUE TITLE
Sobre Sesión 3 de revisión de proyectos digitales

### ISSUE THREAD

**Issue by mariajoafana** [mariajoafana/introduccion_humanidades_digitales#1]
Hola @1cgonza Se me ocurre que en esta sesión yo puedo mostrar algunos ejemplos viejos (tipo 1990s a comienzos de los 2000) de proyectos HD de campos tradicionales de las humanidades (historia, literatura, musicología e historia del arte) y que tu muestres ejemplos de proyectos de unas humanidades contemporáneas más expansivas, abiertas e interdisciplinarias con ejemplos con arte y periodismo y proyectos más nuevos (2010s al presente). ¿Qué opinas?

**Comment by 1cgonza** [comment]
@mariajoafana perfecto, me parece muy bien
