### ISSUE TITLE
Critical Digital Humaniities Thinking 

### ISSUE THREAD

**Issue by lopezclau** [mariajoafana/introduccion_humanidades_digitales#3]
La liga del Centro en la Universudad de Toronto

https://dhn.utoronto.ca/

Y esta liga es para el funding que pfrecen https://dhn.utoronto.ca/funding/
![image](https://github.com/mariajoafana/introduccion_humanidades_digitales/assets/173946339/37f94fc7-9282-431b-ad17-27547483b122)

**Comment by 1cgonza** [comment]
Gracias @lopezclau, ya quedó en https://github.com/mariajoafana/introduccion_humanidades_digitales/blob/main/Proyecto_Final.md
